<?php

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;


/**
 * Implements hook_requirements_alter().
 */
function mute_afiv_requirement_requirements_alter(array &$requirements, $phase): void
{
//  Drupal::logger('requirements_alter')->debug("Requirements alter called");
//  dpm($requirements,'requirements');
//  dpm($phase,'phase');

  //if ($phase !== 'runtime') {
  //  return;
  //}
  // Remove the "Supported image file formats" row entirely.
  if (isset($requirements['image.toolkit.gd.version'])) {
    unset($requirements['image.toolkit.gd.version']);
  }


}

/**
 * Implements hook_help().
 */
function mute_afiv_requirement_help(string $route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.mute_afiv_requirement':
      dpm($route_match);
      $url = Url::fromRoute('system.status'); // Status report route name.
      $link = $url->toString();

      return t(
        'This module hides the AVIF-related requirement warning from the <a href=":link">Status report</a>.

<h2>Overview</h2>
<p>
  The <strong>Mute AVIF Requirement</strong> module removes the
  “Supported image file formats” row from the Status report and downgrades any
  AVIF-related requirements to <em>OK</em> with no description during runtime.
</p>

<p>This is what the warning looks like:<br />
  <i>2.3.3<br />
  Supported image file formats: GIF, JPEG, PNG, WEBP.<br />
  Unsupported image file format: AVIF.<br />
  Check the PHP GD installation documentation if you want to add support.<br />
  AVIF is not supported, likely because of PHP missing a codec for encoding images. See the change record for more information.<br />
  </i>

</p>

<h2>Use case</h2>
<p>
  Enabling this module is useful when AVIF support is intentionally disabled or not needed,
  This module will then keep the Status report clean and focused on actionable issues.
</p>



              ',
        [
          ':link' => $link,
        ]);

    default:
      return NULL;
  }
}
