<?php

declare(strict_types=1);

namespace Drupal\ai_logging_fix\Routing;

use Drupal\Core\Routing\RouteSubscriberBase;
use Symfony\Component\Routing\RouteCollection;

/**
 * Adjusts AI Logging routes so they do not show in Admin Toolbar menus.
 */
final class RouteSubscriber extends RouteSubscriberBase {

  /**
   * {@inheritdoc}
   */
  protected function alterRoutes(RouteCollection $collection): void {
    // Field UI routes generated by the ai_logging module that leak into the
    // admin toolbar because they are marked as admin routes.
    $route_ids = [
      'entity.ai_log_type.field_ui_fields',
      'entity.ai_log_type.field_ui_form_display',
      'entity.ai_log_type.field_ui_display',
      // Entity edit/add routes also show up in Admin Toolbar.
      'entity.ai_log_type.edit_form',
      'entity.ai_log_type.add_form',
      'entity.ai_log_type.delete_form',
    ];

    foreach ($route_ids as $route_id) {
      if (!$collection->get($route_id)) {
        continue;
      }
      $route = $collection->get($route_id);
      // Keep the routes available but stop Admin Toolbar from promoting them
      // into the menu by removing the admin marker.
      $route->setOption('_admin_route', FALSE);
      // Also prevent admin menu discovery from inheriting the admin flag.
      $route->setDefault('_admin_route', FALSE);
    }
  }

}
